// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: stats.proto

package server

import (
	"context"

	"Anitale/apps/stats/rpc/internal/logic"
	"Anitale/apps/stats/rpc/internal/svc"
	"Anitale/apps/stats/rpc/pb"
)

type StatsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStatsServer
}

func NewStatsServer(svcCtx *svc.ServiceContext) *StatsServer {
	return &StatsServer{
		svcCtx: svcCtx,
	}
}

// 按热度排序, 返回排序完成的 anime_id 列表
func (s *StatsServer) SortByHot(ctx context.Context, in *pb.SortByHotReq) (*pb.SortByHotResp, error) {
	l := logic.NewSortByHotLogic(ctx, s.svcCtx)
	return l.SortByHot(in)
}
