// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package userservice

import (
	"context"

	"Anitale/apps/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserPreferencesRequest     = pb.GetUserPreferencesRequest
	GetUserPreferencesResponse    = pb.GetUserPreferencesResponse
	GetUserProfileRequest         = pb.GetUserProfileRequest
	GetUserProfileResponse        = pb.GetUserProfileResponse
	LoginUserRequest              = pb.LoginUserRequest
	LoginUserResponse             = pb.LoginUserResponse
	RegisterUserRequest           = pb.RegisterUserRequest
	RegisterUserResponse          = pb.RegisterUserResponse
	UpdateUserPreferencesRequest  = pb.UpdateUserPreferencesRequest
	UpdateUserPreferencesResponse = pb.UpdateUserPreferencesResponse
	UpdateUserProfileRequest      = pb.UpdateUserProfileRequest
	UpdateUserProfileResponse     = pb.UpdateUserProfileResponse
	User                          = pb.User
	UserPreferences               = pb.UserPreferences
	UserProfile                   = pb.UserProfile

	UserService interface {
		// 用户注册
		RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
		// 用户登录
		LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
		// 获取用户个人信息
		GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
		// 更新用户个人信息
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error)
		// 更新用户偏好设置
		UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...grpc.CallOption) (*UpdateUserPreferencesResponse, error)
		// 获取用户偏好设置
		GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*GetUserPreferencesResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 用户注册
func (m *defaultUserService) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.RegisterUser(ctx, in, opts...)
}

// 用户登录
func (m *defaultUserService) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.LoginUser(ctx, in, opts...)
}

// 获取用户个人信息
func (m *defaultUserService) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserProfile(ctx, in, opts...)
}

// 更新用户个人信息
func (m *defaultUserService) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserProfile(ctx, in, opts...)
}

// 更新用户偏好设置
func (m *defaultUserService) UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...grpc.CallOption) (*UpdateUserPreferencesResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserPreferences(ctx, in, opts...)
}

// 获取用户偏好设置
func (m *defaultUserService) GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*GetUserPreferencesResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserPreferences(ctx, in, opts...)
}
