// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: anime.proto

package anime

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"

	"Anitale/apps/anime/rpc/pb"
)

type (
	AddAnimeReq     = pb.AddAnimeReq
	AddAnimeResp    = pb.AddAnimeResp
	AnimeListReq    = pb.AnimeListReq
	AnimeListResp   = pb.AnimeListResp
	DeleteAnimeReq  = pb.DeleteAnimeReq
	DeleteAnimeResp = pb.DeleteAnimeResp
	Item            = pb.Item
	UpdateAnimeReq  = pb.UpdateAnimeReq
	UpdateAnimeResp = pb.UpdateAnimeResp

	Anime interface {
		AnimeAdd(ctx context.Context, in *AddAnimeReq, opts ...grpc.CallOption) (*AddAnimeResp, error)
		AnimeDelete(ctx context.Context, in *DeleteAnimeReq, opts ...grpc.CallOption) (*DeleteAnimeResp, error)
		AnimeUpdate(ctx context.Context, in *UpdateAnimeReq, opts ...grpc.CallOption) (*UpdateAnimeResp, error)
		// 多条件分页查询
		AnimeList(ctx context.Context, in *AnimeListReq, opts ...grpc.CallOption) (*AnimeListResp, error)
	}

	defaultAnime struct {
		cli zrpc.Client
	}
)

func NewAnime(cli zrpc.Client) Anime {
	return &defaultAnime{
		cli: cli,
	}
}

func (m *defaultAnime) AnimeAdd(ctx context.Context, in *AddAnimeReq, opts ...grpc.CallOption) (*AddAnimeResp, error) {
	client := pb.NewAnimeClient(m.cli.Conn())
	return client.AnimeAdd(ctx, in, opts...)
}

func (m *defaultAnime) AnimeDelete(ctx context.Context, in *DeleteAnimeReq, opts ...grpc.CallOption) (*DeleteAnimeResp, error) {
	client := pb.NewAnimeClient(m.cli.Conn())
	return client.AnimeDelete(ctx, in, opts...)
}

func (m *defaultAnime) AnimeUpdate(ctx context.Context, in *UpdateAnimeReq, opts ...grpc.CallOption) (*UpdateAnimeResp, error) {
	client := pb.NewAnimeClient(m.cli.Conn())
	return client.AnimeUpdate(ctx, in, opts...)
}

// 多条件分页查询
func (m *defaultAnime) AnimeList(ctx context.Context, in *AnimeListReq, opts ...grpc.CallOption) (*AnimeListResp, error) {
	client := pb.NewAnimeClient(m.cli.Conn())
	return client.AnimeList(ctx, in, opts...)
}
