// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: anime.proto

package animeclient

import (
	"context"

	"Anitale/apps/anime/rpc/anime"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnimeAddReq     = anime.AnimeAddReq
	AnimeAddResp    = anime.AnimeAddResp
	AnimeDeleteReq  = anime.AnimeDeleteReq
	AnimeDeleteResp = anime.AnimeDeleteResp
	AnimeListReq    = anime.AnimeListReq
	AnimeListResp   = anime.AnimeListResp
	AnimeUpdateReq  = anime.AnimeUpdateReq
	AnimeUpdateResp = anime.AnimeUpdateResp
	Item            = anime.Item
	PageByCondReq   = anime.PageByCondReq
	PageByCondResp  = anime.PageByCondResp

	Anime interface {
		AnimeAdd(ctx context.Context, in *AnimeAddReq, opts ...grpc.CallOption) (*AnimeAddResp, error)
		AnimeDelete(ctx context.Context, in *AnimeDeleteReq, opts ...grpc.CallOption) (*AnimeDeleteResp, error)
		AnimeUpdate(ctx context.Context, in *AnimeUpdateReq, opts ...grpc.CallOption) (*AnimeUpdateResp, error)
		AnimeList(ctx context.Context, in *AnimeListReq, opts ...grpc.CallOption) (*AnimeListResp, error)
		PageByCond(ctx context.Context, in *PageByCondReq, opts ...grpc.CallOption) (*PageByCondResp, error)
	}

	defaultAnime struct {
		cli zrpc.Client
	}
)

func NewAnime(cli zrpc.Client) Anime {
	return &defaultAnime{
		cli: cli,
	}
}

func (m *defaultAnime) AnimeAdd(ctx context.Context, in *AnimeAddReq, opts ...grpc.CallOption) (*AnimeAddResp, error) {
	client := anime.NewAnimeClient(m.cli.Conn())
	return client.AnimeAdd(ctx, in, opts...)
}

func (m *defaultAnime) AnimeDelete(ctx context.Context, in *AnimeDeleteReq, opts ...grpc.CallOption) (*AnimeDeleteResp, error) {
	client := anime.NewAnimeClient(m.cli.Conn())
	return client.AnimeDelete(ctx, in, opts...)
}

func (m *defaultAnime) AnimeUpdate(ctx context.Context, in *AnimeUpdateReq, opts ...grpc.CallOption) (*AnimeUpdateResp, error) {
	client := anime.NewAnimeClient(m.cli.Conn())
	return client.AnimeUpdate(ctx, in, opts...)
}

func (m *defaultAnime) AnimeList(ctx context.Context, in *AnimeListReq, opts ...grpc.CallOption) (*AnimeListResp, error) {
	client := anime.NewAnimeClient(m.cli.Conn())
	return client.AnimeList(ctx, in, opts...)
}

func (m *defaultAnime) PageByCond(ctx context.Context, in *PageByCondReq, opts ...grpc.CallOption) (*PageByCondResp, error) {
	client := anime.NewAnimeClient(m.cli.Conn())
	return client.PageByCond(ctx, in, opts...)
}
