// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: apps/stats/rpc/desc/proto/stats.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeId      int64                `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	ViewCount    int64                `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount    int64                `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount int64                `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ShareCount   int64                `protobuf:"varint,5,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	LastUpdated  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

func (x *Item) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Item) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Item) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Item) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Item) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// 增加一条 stats 数据
type AddStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeId      int64 `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	ViewCount    int64 `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount    int64 `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount int64 `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ShareCount   int64 `protobuf:"varint,5,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
}

func (x *AddStatsReq) Reset() {
	*x = AddStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStatsReq) ProtoMessage() {}

func (x *AddStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStatsReq.ProtoReflect.Descriptor instead.
func (*AddStatsReq) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *AddStatsReq) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

func (x *AddStatsReq) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *AddStatsReq) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *AddStatsReq) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *AddStatsReq) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

type AddStatsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeId int64 `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
}

func (x *AddStatsResp) Reset() {
	*x = AddStatsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStatsResp) ProtoMessage() {}

func (x *AddStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStatsResp.ProtoReflect.Descriptor instead.
func (*AddStatsResp) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *AddStatsResp) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

// 删除一条 stats 数据
type DeleteStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeId int64 `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
}

func (x *DeleteStatsReq) Reset() {
	*x = DeleteStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStatsReq) ProtoMessage() {}

func (x *DeleteStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStatsReq.ProtoReflect.Descriptor instead.
func (*DeleteStatsReq) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteStatsReq) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

type DeleteStatsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeId int64 `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
}

func (x *DeleteStatsResp) Reset() {
	*x = DeleteStatsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStatsResp) ProtoMessage() {}

func (x *DeleteStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStatsResp.ProtoReflect.Descriptor instead.
func (*DeleteStatsResp) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteStatsResp) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

// 修改一条 stats 数据
type UpdateStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeId      int64 `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	ViewCount    int64 `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount    int64 `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount int64 `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ShareCount   int64 `protobuf:"varint,5,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
}

func (x *UpdateStatsReq) Reset() {
	*x = UpdateStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatsReq) ProtoMessage() {}

func (x *UpdateStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatsReq.ProtoReflect.Descriptor instead.
func (*UpdateStatsReq) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStatsReq) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

func (x *UpdateStatsReq) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *UpdateStatsReq) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *UpdateStatsReq) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *UpdateStatsReq) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

type UpdateStatsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeId      int64                `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	ViewCount    int64                `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount    int64                `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount int64                `protobuf:"varint,4,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ShareCount   int64                `protobuf:"varint,5,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	LastUpdated  *timestamp.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *UpdateStatsResp) Reset() {
	*x = UpdateStatsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatsResp) ProtoMessage() {}

func (x *UpdateStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatsResp.ProtoReflect.Descriptor instead.
func (*UpdateStatsResp) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStatsResp) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

func (x *UpdateStatsResp) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *UpdateStatsResp) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *UpdateStatsResp) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *UpdateStatsResp) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *UpdateStatsResp) GetLastUpdated() *timestamp.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// 按热度排序
type SortByHotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeIds []int64 `protobuf:"varint,1,rep,packed,name=anime_ids,json=animeIds,proto3" json:"anime_ids,omitempty"`
}

func (x *SortByHotReq) Reset() {
	*x = SortByHotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortByHotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortByHotReq) ProtoMessage() {}

func (x *SortByHotReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortByHotReq.ProtoReflect.Descriptor instead.
func (*SortByHotReq) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{7}
}

func (x *SortByHotReq) GetAnimeIds() []int64 {
	if x != nil {
		return x.AnimeIds
	}
	return nil
}

type SortByHotResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeIds []int64 `protobuf:"varint,1,rep,packed,name=anime_ids,json=animeIds,proto3" json:"anime_ids,omitempty"`
}

func (x *SortByHotResp) Reset() {
	*x = SortByHotResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortByHotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortByHotResp) ProtoMessage() {}

func (x *SortByHotResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortByHotResp.ProtoReflect.Descriptor instead.
func (*SortByHotResp) Descriptor() ([]byte, []int) {
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP(), []int{8}
}

func (x *SortByHotResp) GetAnimeIds() []int64 {
	if x != nil {
		return x.AnimeIds
	}
	return nil
}

var File_apps_stats_rpc_desc_proto_stats_proto protoreflect.FileDescriptor

var file_apps_stats_rpc_desc_proto_stats_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x72, 0x70, 0x63,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x69, 0x65,
	0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c,
	0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x0b, 0x41,
	0x64, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6e,
	0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e,
	0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x0c, 0x41, 0x64, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49,
	0x64, 0x22, 0x2c, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22,
	0xaf, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0xef, 0x01, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x2b, 0x0a, 0x0c, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x73,
	0x22, 0x2c, 0x0a, 0x0d, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x73, 0x32, 0x47,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x3e, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x42,
	0x79, 0x48, 0x6f, 0x74, 0x12, 0x17, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x2e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x48, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79,
	0x48, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_stats_rpc_desc_proto_stats_proto_rawDescOnce sync.Once
	file_apps_stats_rpc_desc_proto_stats_proto_rawDescData = file_apps_stats_rpc_desc_proto_stats_proto_rawDesc
)

func file_apps_stats_rpc_desc_proto_stats_proto_rawDescGZIP() []byte {
	file_apps_stats_rpc_desc_proto_stats_proto_rawDescOnce.Do(func() {
		file_apps_stats_rpc_desc_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_stats_rpc_desc_proto_stats_proto_rawDescData)
	})
	return file_apps_stats_rpc_desc_proto_stats_proto_rawDescData
}

var file_apps_stats_rpc_desc_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apps_stats_rpc_desc_proto_stats_proto_goTypes = []any{
	(*Item)(nil),                // 0: analytics.Item
	(*AddStatsReq)(nil),         // 1: analytics.AddStatsReq
	(*AddStatsResp)(nil),        // 2: analytics.AddStatsResp
	(*DeleteStatsReq)(nil),      // 3: analytics.DeleteStatsReq
	(*DeleteStatsResp)(nil),     // 4: analytics.DeleteStatsResp
	(*UpdateStatsReq)(nil),      // 5: analytics.UpdateStatsReq
	(*UpdateStatsResp)(nil),     // 6: analytics.UpdateStatsResp
	(*SortByHotReq)(nil),        // 7: analytics.SortByHotReq
	(*SortByHotResp)(nil),       // 8: analytics.SortByHotResp
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_apps_stats_rpc_desc_proto_stats_proto_depIdxs = []int32{
	9, // 0: analytics.Item.last_updated:type_name -> google.protobuf.Timestamp
	9, // 1: analytics.UpdateStatsResp.last_updated:type_name -> google.protobuf.Timestamp
	7, // 2: analytics.stats.SortByHot:input_type -> analytics.SortByHotReq
	8, // 3: analytics.stats.SortByHot:output_type -> analytics.SortByHotResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apps_stats_rpc_desc_proto_stats_proto_init() }
func file_apps_stats_rpc_desc_proto_stats_proto_init() {
	if File_apps_stats_rpc_desc_proto_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddStatsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteStatsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SortByHotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_stats_rpc_desc_proto_stats_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SortByHotResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_stats_rpc_desc_proto_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_stats_rpc_desc_proto_stats_proto_goTypes,
		DependencyIndexes: file_apps_stats_rpc_desc_proto_stats_proto_depIdxs,
		MessageInfos:      file_apps_stats_rpc_desc_proto_stats_proto_msgTypes,
	}.Build()
	File_apps_stats_rpc_desc_proto_stats_proto = out.File
	file_apps_stats_rpc_desc_proto_stats_proto_rawDesc = nil
	file_apps_stats_rpc_desc_proto_stats_proto_goTypes = nil
	file_apps_stats_rpc_desc_proto_stats_proto_depIdxs = nil
}
