// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type Anime struct {
	Title      string `json:"title"`
	ImgURL     string `json:"img_url"`
	Tag        string `json:"tag"`
	UpdateTime int64  `json:"update_time"`
}

type AnimeListReq struct {
	Page      int64  `json:"page,defaule=1"`
	PageSize  int32  `form:"page_size,default=20"`
	Country   string `json:"country,optional"`
	Tag       string `json:"tag,optional"`
	AnimeType string `json:"anime_type,optional"`
}

type AnimeListResp struct {
	Base
	Data []*Anime `json:"data"`
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
}

type UserInfoUpdateReq struct {
}

type UserInfoUpdateResp struct {
}

type UserLoginReq struct {
}

type UserLoginResp struct {
}
