// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: anime.proto

package server

import (
	"context"

	"Anitale/apps/anime/rpc/internal/logic"
	"Anitale/apps/anime/rpc/internal/svc"
	"Anitale/apps/anime/rpc/pb"
)

type AnimeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAnimeServer
}

func NewAnimeServer(svcCtx *svc.ServiceContext) *AnimeServer {
	return &AnimeServer{
		svcCtx: svcCtx,
	}
}

func (s *AnimeServer) GetAnime(ctx context.Context, in *pb.GetAnimeReq) (*pb.GetAnimeResp, error) {
	l := logic.NewGetAnimeLogic(ctx, s.svcCtx)
	return l.GetAnime(in)
}

func (s *AnimeServer) AddAnime(ctx context.Context, in *pb.AddAnimeReq) (*pb.AddAnimeResp, error) {
	l := logic.NewAddAnimeLogic(ctx, s.svcCtx)
	return l.AddAnime(in)
}

func (s *AnimeServer) DeleteAnime(ctx context.Context, in *pb.DeleteAnimeReq) (*pb.DeleteAnimeResp, error) {
	l := logic.NewDeleteAnimeLogic(ctx, s.svcCtx)
	return l.DeleteAnime(in)
}

func (s *AnimeServer) UpdateAnime(ctx context.Context, in *pb.UpdateAnimeReq) (*pb.UpdateAnimeResp, error) {
	l := logic.NewUpdateAnimeLogic(ctx, s.svcCtx)
	return l.UpdateAnime(in)
}

// 多条件分页查询
func (s *AnimeServer) AnimeList(ctx context.Context, in *pb.AnimeListReq) (*pb.AnimeListResp, error) {
	l := logic.NewAnimeListLogic(ctx, s.svcCtx)
	return l.AnimeList(in)
}
